# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/1.0.0/tag_publish/schema.json

node:
  packages:
    - {}
  repository:
    github:
      host: npm.pkg.github.com
    npm:
      host: registry.npmjs.org
dispatch:
  - {}
