# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/0.11.0/tag_publish/schema.json

node:
  packages:
    - {}
  repositories:
    github:
      host: npm.pkg.github.com
    npm:
      host: registry.npmjs.org
